name: Release

on:
  push:
    branches: [ master ]

  
jobs:
  release:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: SiqiLu/dotnet-bump-version@master
      with:
          # Version files to bump version.
          # You can use Glob pattern string (like "**/*.csproj") or Glob patterns array json string (like "["**/*.csproj", "v1.version", "**/*.version.json", "!v2.version.json"]").
          # Patterns supported by Globby are supported.Leading ! changes the meaning of an include pattern to exclude.
          version_file: src/Nager.Date/Nager.Date.csproj

          github_token: ${{ secrets.GITHUB_TOKEN }}
